# Generated by Django 2.0.5 on 2021-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_certificate1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=300)),
                ('caste', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('mother_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
                ('sname', models.CharField(max_length=300)),
                ('dateof_admission', models.CharField(max_length=300)),
                ('last_studiedclass', models.CharField(max_length=300)),
                ('reason_leaving', models.CharField(max_length=300)),
                ('issue_date', models.CharField(max_length=300)),
                ('general_conduct', models.CharField(max_length=300)),
            ],
        ),
    ]
