# Generated by Django 2.0.5 on 2021-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_transfer_certificate1'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_certificate1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('sch_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='attendance_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('sch_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
    ]
