# Generated by Django 2.0.5 on 2021-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_attendance_certificate1_attendance_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_certificate1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('sch_name', models.CharField(max_length=200)),
                ('sports_name', models.CharField(max_length=200)),
                ('winning_place', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='sports_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('sch_name', models.CharField(max_length=200)),
                ('sports_name', models.CharField(max_length=200)),
                ('winning_place', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
