# Generated by Django 2.0.5 on 2021-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_sports_certificate1_sports_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_certificate1',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sports_certificate1',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer_certificate1',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_certificate1',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sports_certificate1',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer_certificate1',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
    ]
