# Generated by Django 2.0.5 on 2021-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210206_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_birth1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestor', models.CharField(max_length=300)),
                ('studnet_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('certificate_name', models.CharField(max_length=200)),
                ('status1', models.CharField(max_length=200)),
                ('key1', models.CharField(max_length=200)),
            ],
        ),
    ]
