# Generated by Django 2.0.5 on 2021-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctransfer_certificate1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=300)),
                ('caste', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('mother_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
                ('sname', models.CharField(max_length=300)),
                ('dateof_admission', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('joining_year', models.CharField(max_length=300)),
                ('degree_finishingyear', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
