# Generated by Django 2.0.5 on 2021-02-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_ctransfer_certificate1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctransfer_certificate1',
            old_name='sname',
            new_name='cname',
        ),
    ]
