# Generated by Django 2.0.5 on 2021-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20210204_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctransfer_certificate1',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree_certificate11',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctransfer_certificate1',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='degree_certificate11',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
    ]
