# Generated by Django 2.0.5 on 2021-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='office_register1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
