# Generated by Django 2.0.5 on 2021-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_emppay_slip_salary_slip'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp_certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('exp_year', models.CharField(max_length=300)),
                ('starting_year', models.CharField(max_length=300)),
                ('finishing_year', models.CharField(max_length=300)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='experience1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('exp_year', models.CharField(max_length=300)),
                ('starting_year', models.CharField(max_length=300)),
                ('finishing_year', models.CharField(max_length=300)),
            ],
        ),
    ]
