# Generated by Django 2.0.5 on 2021-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_exp_certificate_experience1'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_certificate',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exp_certificate',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='salary_slip',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
    ]
