# Generated by Django 2.0.5 on 2021-01-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birth_details',
            new_name='bkey_request1',
        ),
    ]
