# Generated by Django 2.0.5 on 2021-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20210120_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkey_request1',
            name='key1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
