# Generated by Django 2.0.5 on 2021-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_bkey_request1_key1'),
    ]

    operations = [
        migrations.CreateModel(
            name='birth_certificate1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('per_name', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=200)),
                ('birth_place', models.CharField(max_length=300)),
                ('dateof_birth', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('mother_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('work_requirements', models.FileField(upload_to='')),
            ],
        ),
    ]
