# Generated by Django 2.0.5 on 2021-01-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0004_birth_certificate1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth_certificate1',
            old_name='work_requirements',
            new_name='file_path',
        ),
    ]
