# Generated by Django 2.0.5 on 2021-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_auto_20210122_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth_certificate1',
            name='atimestamp',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth_certificate1',
            name='newhash1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth_certificate1',
            name='phash1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
