# Generated by Django 2.0.5 on 2021-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0007_community_certificate1'),
    ]

    operations = [
        migrations.CreateModel(
            name='genration_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('member_count', models.CharField(max_length=300)),
                ('file_path', models.FileField(upload_to='')),
                ('phash1', models.CharField(max_length=300)),
                ('newhash1', models.CharField(max_length=300)),
                ('atimestamp', models.CharField(max_length=300)),
            ],
        ),
    ]
