# Generated by Django 2.0.5 on 2021-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0008_genration_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='genration_card',
            name='certificate_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genration_card',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
    ]
