# Generated by Django 2.0.5 on 2021-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0011_auto_20210206_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth_certificate1',
            old_name='per_name',
            new_name='uname',
        ),
    ]
