from django.db import models

# Create your models here.
class college_register1(models.Model):
    id = models.AutoField(primary_key=True)
    collegename = models.CharField(max_length=300)
    email = models.CharField(max_length=200)
    mobile = models.BigIntegerField()
    password = models.CharField(max_length=200)

class ctransfer_certificate1(models.Model):
    id = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=300)
    full_name = models.CharField(max_length=200)
    dateof_birth = models.CharField(max_length=300)
    religion = models.CharField(max_length=300)
    caste=models.CharField(max_length=300)
    father_name = models.CharField(max_length=300)
    mother_name = models.CharField(max_length=300)
    address = models.CharField(max_length=300)
    file_path =  models.CharField(max_length=300)
    phash1=models.CharField(max_length=300)
    newhash1=models.CharField(max_length=300)
    atimestamp=models.CharField(max_length=300)
    cname = models.CharField(max_length=300)
    dateof_admission = models.CharField(max_length=300)
    degree = models.CharField(max_length=300)
    joining_year = models.CharField(max_length=300)
    degree_finishingyear = models.CharField(max_length=300)
    status = models.CharField(max_length=300)
    university = models.CharField(max_length=300)
    certificate_file = models.FileField()

class degree_certificate11(models.Model):
    id = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=300)
    full_name = models.CharField(max_length=200)
    dateof_birth = models.CharField(max_length=300)
    file_path =  models.CharField(max_length=300)
    phash1=models.CharField(max_length=300)
    newhash1=models.CharField(max_length=300)
    atimestamp=models.CharField(max_length=300)
    cname = models.CharField(max_length=300)
    dateof_admission = models.CharField(max_length=300)
    degree = models.CharField(max_length=300)
    joining_year = models.CharField(max_length=300)
    degree_finishingyear = models.CharField(max_length=300)
    status = models.CharField(max_length=300)
    university = models.CharField(max_length=300)
    certificate_file = models.FileField()