# Generated by Django 2.0.5 on 2021-01-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('uname', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
