# Generated by Django 2.0.5 on 2021-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=200)),
                ('caste', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
            ],
        ),
    ]
