# Generated by Django 2.0.5 on 2021-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_community_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_details1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=200)),
                ('caste', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('dateof_admission', models.CharField(max_length=200)),
                ('last_studiedclass', models.CharField(max_length=200)),
                ('reason_leaving', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=200)),
                ('general_conduct', models.CharField(max_length=200)),
            ],
        ),
    ]
