# Generated by Django 2.0.5 on 2021-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_school_details1'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_details1',
            name='school_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
