# Generated by Django 2.0.5 on 2021-02-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_school_details1_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_details1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=200)),
                ('caste', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('dateof_admission', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('joining_year', models.CharField(max_length=200)),
                ('degree_finishingyear', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
    ]
