# Generated by Django 2.0.5 on 2021-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_college_details1'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_details1',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
