# Generated by Django 2.0.5 on 2021-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_college_details1_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='office_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
