# Generated by Django 2.0.5 on 2021-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_office_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ration_card1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=200)),
                ('dateof_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('member_count', models.CharField(max_length=200)),
            ],
        ),
    ]
