# Generated by Django 2.0.5 on 2021-02-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ration_card1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ration_card1',
            new_name='ration_carddetails',
        ),
    ]
