# Generated by Django 2.0.5 on 2021-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth_details',
            name='birth_place',
            field=models.CharField(max_length=300),
        ),
    ]
